name: Build SDK
on:
  workflow_call:
    inputs:
      version:
        description: 'generated sdk version'
        required: true
        type: string
      name:
        description: 'generated sdk name'
        required: true
        type: string
      fileAsBase64:
        description: 'generated sdk file as base64 encoded'
        required: true
        type: string
jobs:
  generate_sdk_with_auto_version:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - id: Build_with_Maven
        run: mvn clean install
      - name: Generate_SDK_Files
        working-directory: openapi
        run: |
          mvn clean install
          mvn exec:java "-Dnamespace=${{ github.event.inputs.name }}" -DsdkVersion=${{ github.event.inputs.version }} "-Dspec=${{ github.event.inputs.fileAsBase64 }}"
      - uses: actions/upload-artifact@v2
        with:
          name: sdk
          path: ./openapi/target/sdk
