name: Build & Release SDK
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'generated sdk version'
        required: false
        default: ''
      name:
        description: 'generated sdk name'
        required: true
      fileAsBase64:
        description: 'generated sdk file as base64 encoded'
        required: true
jobs:
  generate_sdk_with_auto_version:
    runs-on: macos-latest
    if: ${{ github.event.inputs.version == '' }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - id: Build_with_Maven
        run: mvn clean install
      - name: Generate_SDK_Files
        run: |
          cd openapi/
          mvn clean install
          currentVersion=$(curl --silent https://repo1.maven.org/maven2/com/expediagroup/openworld/sdk/openworld-java-sdk-${{ github.event.inputs.name }}/maven-metadata.xml | xmllint --xpath "/metadata/versioning/latest/text()" -)
          echo "${currentVersion:=0.0.1-alpha}"
          lastCharacter=${currentVersion: -1}
          re='^[0-9]+$'
          if ! [[ $lastCharacter =~ $re ]]; then
            currentVersion="${currentVersion}.1"
          else
            currentVersion="${currentVersion%?}$((lastCharachter+1))"
          fi
          mvn exec:java "-Dnamespace=${{ github.event.inputs.name }}" -DsdkVersion=$currentVersion "-Dspec=${{ github.event.inputs.fileAsBase64 }}"
      - uses: actions/upload-artifact@v2
        with:
          name: sdk
          path: ./openapi/target/sdk
  generate_sdk_with_provided_version:
    runs-on: macos-latest
    if: ${{ github.event.inputs.version != '' }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - id: Build_with_Maven
        run: mvn clean install
      - name: Generate_SDK_Files
        run: |
          cd openapi/
          mvn clean install
          mvn exec:java "-Dnamespace=${{ github.event.inputs.name }}" "-DsdkVersion=${{ github.event.inputs.version }}" "-Dspec=${{ github.event.inputs.fileAsBase64 }}"
      - uses: actions/upload-artifact@v2
        with:
          name: sdk
          path: ./openapi/target/sdk
  deploy_sdk:
    needs: [generate_sdk_with_auto_version,generate_sdk_with_provided_version]
    uses: ./.github/workflows/github-release-actions.yml
    secrets: inherit
  update-bom:
    needs: deploy_sdk
    runs-on: ubuntu-latest
    steps:
      - name: Update BOM
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.github.com/repos/ExpediaGroup/openworld-sdk-java/actions/workflows/update-bom-version-actions.yml/dispatches'
          method: 'POST'
          customHeaders: '{"Authorization": "${{secrets.CUSTOM_TOKEN}}","Accept": "application/vnd.github+json"}'
          data: '{"ref":"main","inputs":{"sdk-version":"${{ inputs.version }}","sdk-name":"openworld-java-sdk-${{ inputs.name }}"}}'
