name: Build & Release SDK
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'generated sdk version'
        required: false
        default: ''
      name:
        description: 'generated sdk name'
        required: true
      fileAsBase64:
        description: 'generated sdk file as base64 encoded'
        required: true
jobs:
  prepare_sdk_version_if_not_provided:
    if: ${{ github.event.inputs.version == '' }}
    runs-on: macos-latest
    outputs:
      version: ${{ steps.prepare_sdk_version.outputs.version }}
    steps:
      - id: get_version
        run: |
          currentVersion=$(curl --silent https://repo1.maven.org/maven2/com/expediagroup/openworld/sdk/openworld-java-sdk-fraudprevention/maven-metadata.xml | xmllint --xpath "/metadata/versioning/latest/text()" -) || echo "${currentVersion:=0.0.1-alpha}"
          lastCharacter=${currentVersion: -1}
          re='^[0-9]+$'
          if ! [[ $lastCharacter =~ $re ]]; then
            currentVersion="${currentVersion}.1"
          else
            currentVersion="${currentVersion%?}$((lastCharacter+1))"
          fi
          echo "::set-output name=version::${currentVersion}"
  generate_sdk_with_auto_version:
    if: ${{ github.event.inputs.version == '' }}
    uses: ./.github/workflows/generate-sdk-actions.yml
    needs: [prepare_sdk_version_if_not_provided]
    with:
      version: ${{ needs.prepare_sdk_version_if_not_provided.outputs.version }}
      name: ${{ github.event.inputs.name }}
      fileAsBase64: ${{ github.event.inputs.fileAsBase64 }}
  generate_sdk_with_provided_version:
    if: ${{ github.event.inputs.version != '' }}
    uses: ./.github/workflows/generate-sdk-actions.yml
    with:
      version: ${{ github.event.inputs.version }}
      name: ${{ github.event.inputs.name }}
      fileAsBase64: ${{ github.event.inputs.fileAsBase64 }}

  deploy_sdk:
    if: ${{ always() && contains(needs.*.result, 'success') && !(contains(needs.*.result, 'failure')) }}
    needs: [ generate_sdk_with_auto_version,generate_sdk_with_provided_version ]
    uses: ./.github/workflows/github-release-actions.yml
    secrets: inherit
  update-bom:
    needs: deploy_sdk
    runs-on: ubuntu-latest
    steps:
      - name: Update BOM
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.github.com/repos/ExpediaGroup/openworld-sdk-java/actions/workflows/update-bom-version-actions.yml/dispatches'
          method: 'POST'
          customHeaders: '{"Authorization": "${{secrets.CUSTOM_TOKEN}}","Accept": "application/vnd.github+json"}'
          data: '{"ref":"main","inputs":{"sdk-version":"${{ inputs.version }}","sdk-name":"openworld-java-sdk-${{ inputs.name }}"}}'
